services:
  # Serviço da API
  api:
    build: .
    ports:
      - "3333:3000"
    depends_on:
      - postgres
    env_file: # Usando o arquivo .env
      - .env
    volumes:
      - .:/app

  # Serviço do PostgreSQL
  postgres:
    image: postgres:latest
    environment:
      TYPEORM_PORT: 5432
      TYPEORM_USERNAME: postgres
      POSTGRES_PASSWORD: toor
      TYPEORM_DATABASE: ecommerce-api
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - /usr/src/app/node_modules/

# Volumes para persistir os dados do PostgreSQL
volumes:
  postgres-data:
