services:
  # Serviço da API
  api:
    build: .
    image: ecommerce-api-api:latest
    ports:
      - "3000:3300"
    depends_on:
      - postgres
    env_file: # Usando o arquivo .env
      - .env
    working_dir: /app
    command: >
      sh -c "./wait-for-it.sh postgres:5432 -- npm run migration:run && npm start"

  # Serviço do PostgreSQL
  postgres:
    image: postgres:latest
    environment:
      TYPEORM_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: ecommerce-api
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

# Volumes para persistir os dados do PostgreSQL
volumes:
  postgres-data:
