version: "3.8"

services:
  # API service
  api:
    build: .
    image: ecommerce-api-api:latest
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    working_dir: /app
    command: sh -c "npx typeorm migration:run -d dist/src/data-source.js && node dist/src/index.js"

  # PostgreSQL service
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: ecommerce-api
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

# Volumes for PostgreSQL data persistence
volumes:
  postgres-data:
