version: "3"

services:
  # Serviço da API
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules # Ensures node_modules are not overwritten on the host
    working_dir: /app
    command: bash -c "npm install && npm run start"

  # Serviço do PostgreSQL
  postgres:
    image: postgres:latest
    environment:
      TYPEORM_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: ecommerce-api
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

# Volumes para persistir os dados do PostgreSQL
volumes:
  postgres-data:
