version: "3"

services:
  # Serviço da API
  api:
    build: .
    ports:
      - "3333:3300"
    depends_on:
      - postgres
    env_file: # Usando o arquivo .env
      - .env
    volumes:
      - .:/app
      - /app/node_modules # Evita sobrescrever node_modules no host
    working_dir: /app
    command: bash -c "npm install && npm run start" # Instala dependências no container

  # Serviço do PostgreSQL
  postgres:
    image: postgres:latest
    environment:
      TYPEORM_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: ecommerce-api
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

# Volumes para persistir os dados do PostgreSQL
volumes:
  postgres-data:
